// eslint-disable-next-line import/no-anonymous-default-export
export default [
          {
                    "name": "Lira Earrings",
                    "id": 1,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["fashion", "style"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_01.jpeg", "img/Img_01.jpeg", "img/Img_01.jpeg"],
                    "price": 32,
                    "sale": true,
                    "instock": true,
                    "weight": "30",
                    "dimentions": ["15", "10", "1"],
                    "material": "gold"
          },
          {
                    "name": "Hal Earrings",
                    "id": 2,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["accessories"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_02.jpeg", "img/Img_02.jpeg", "img/Img_02.jpeg"],
                    "price": 28,
                    "sale": false,
                    "instock": true,
                    "weight": "78",
                    "dimentions": ["15", "10", "1"],
                    "material": "silver"
          },
          {
                    "name": "Kaede Hair Pin Set Of 3",
                    "id": 3,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["fashion"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_03.jpeg", "img/Img_03.jpeg", "img/Img_03.jpeg"],
                    "price": 30,
                    "sale": false,
                    "instock": true,
                    "weight": "100",
                    "dimentions": ["10", "11", "1"],
                    "material": "Metal"
          },
          {
                    "name": "Hair Pin Set of 3",
                    "id": 4,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["style"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_04.jpeg", "img/Img_04.jpeg", "img/Img_04.jpeg"],
                    "price": 100,
                    "sale": false,
                    "instock": true,
                    "weight": "120",
                    "dimentions": ["10", "11", "1"],
                    "material": "silver"
          },
          {
                    "name": "Plaine Necklace",
                    "id": 5,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["season", "style"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_05.jpeg", "img/Img_05.jpeg", "img/Img_05.jpeg"],
                    "price": 19,
                    "sale": true,
                    "instock": true,
                    "weight": "30",
                    "dimentions": ["23", "13", "2"],
                    "material": "silver"
          },
          {
                    "name": "Yuki Hair Pin Set of 3",
                    "id": 6,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["season", "style"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_06.jpeg", "img/Img_06.jpeg", "img/Img_06.jpeg"],
                    "price": 23,
                    "sale": true,
                    "instock": false,
                    "weight": "39",
                    "dimentions": ["19", "13", "2"],
                    "material": "metal"
          },
          {
                    "name": "Lira Earrings",
                    "id": 7,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["fashion", "style"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_01.jpeg", "img/Img_01.jpeg", "img/Img_01.jpeg"],
                    "price": 32,
                    "sale": true,
                    "instock": true,
                    "weight": "30",
                    "dimentions": ["15", "10", "1"],
                    "material": "gold"
          },
          {
                    "name": "Hal Earrings",
                    "id": 8,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["accessories"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_02.jpeg", "img/Img_02.jpeg", "img/Img_02.jpeg"],
                    "price": 28,
                    "sale": false,
                    "instock": true,
                    "weight": "78",
                    "dimentions": ["15", "10", "1"],
                    "material": "silver"
          },
          {
                    "name": "Kaede Hair Pin Set Of 3",
                    "id": 9,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["fashion"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_03.jpeg", "img/Img_03.jpeg", "img/Img_03.jpeg"],
                    "price": 30,
                    "sale": false,
                    "instock": true,
                    "weight": "100",
                    "dimentions": ["10", "11", "1"],
                    "material": "Metal"
          },
          {
                    "name": "Hair Pin Set of 3",
                    "id": 10,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["style"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_04.jpeg", "img/Img_04.jpeg", "img/Img_04.jpeg"],
                    "price": 100,
                    "sale": false,
                    "instock": true,
                    "weight": "120",
                    "dimentions": ["10", "11", "1"],
                    "material": "silver"
          },
          {
                    "name": "Plaine Necklace",
                    "id": 11,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["season", "style"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_05.jpeg", "img/Img_05.jpeg", "img/Img_05.jpeg"],
                    "price": 19,
                    "sale": true,
                    "instock": true,
                    "weight": "30",
                    "dimentions": ["23", "13", "2"],
                    "material": "silver"
          },
          {
                    "name": "Yuki Hair Pin Set of 3",
                    "id": 12,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["season", "style"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_06.jpeg", "img/Img_06.jpeg", "img/Img_06.jpeg"],
                    "price": 23,
                    "sale": true,
                    "instock": false,
                    "weight": "39",
                    "dimentions": ["19", "13", "2"],
                    "material": "metal"
          },
          {
                    "name": "Lira Earrings",
                    "id": 13,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["fashion", "style"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_01.jpeg", "img/Img_01.jpeg", "img/Img_01.jpeg"],
                    "price": 32,
                    "sale": true,
                    "instock": true,
                    "weight": "30",
                    "dimentions": ["15", "10", "1"],
                    "material": "gold"
          },
          {
                    "name": "Hal Earrings",
                    "id": 14,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["accessories"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_02.jpeg", "img/Img_02.jpeg", "img/Img_02.jpeg"],
                    "price": 28,
                    "sale": false,
                    "instock": true,
                    "weight": "78",
                    "dimentions": ["15", "10", "1"],
                    "material": "silver"
          },
          {
                    "name": "Kaede Hair Pin Set Of 3",
                    "id": 15,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["fashion"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_03.jpeg", "img/Img_03.jpeg", "img/Img_03.jpeg"],
                    "price": 30,
                    "sale": false,
                    "instock": true,
                    "weight": "100",
                    "dimentions": ["10", "11", "1"],
                    "material": "Metal"
          },
          {
                    "name": "Hair Pin Set of 3",
                    "id": 16,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["style"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_04.jpeg", "img/Img_04.jpeg", "img/Img_04.jpeg"],
                    "price": 100,
                    "sale": false,
                    "instock": true,
                    "weight": "120",
                    "dimentions": ["10", "11", "1"],
                    "material": "silver"
          },
          {
                    "name": "Plaine Necklace",
                    "id": 17,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["season", "style"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_05.jpeg", "img/Img_05.jpeg", "img/Img_05.jpeg"],
                    "price": 19,
                    "sale": true,
                    "instock": true,
                    "weight": "30",
                    "dimentions": ["23", "13", "2"],
                    "material": "silver"
          },
          {
                    "name": "Yuki Hair Pin Set of 3",
                    "id": 18,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["season", "style"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_06.jpeg", "img/Img_06.jpeg", "img/Img_06.jpeg"],
                    "price": 23,
                    "sale": true,
                    "instock": false,
                    "weight": "39",
                    "dimentions": ["19", "13", "2"],
                    "material": "metal"
          },
          {
                    "name": "Lira Earrings",
                    "id": 19,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["fashion", "style"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_01.jpeg", "img/Img_01.jpeg", "img/Img_01.jpeg"],
                    "price": 32,
                    "sale": true,
                    "instock": true,
                    "weight": "30",
                    "dimentions": ["15", "10", "1"],
                    "material": "gold"
          },
          {
                    "name": "Hal Earrings",
                    "id": 20,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["accessories"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_02.jpeg", "img/Img_02.jpeg", "img/Img_02.jpeg"],
                    "price": 28,
                    "sale": false,
                    "instock": true,
                    "weight": "78",
                    "dimentions": ["15", "10", "1"],
                    "material": "silver"
          },
          {
                    "name": "Kaede Hair Pin Set Of 3",
                    "id": 21,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["fashion"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_03.jpeg", "img/Img_03.jpeg", "img/Img_03.jpeg"],
                    "price": 30,
                    "sale": false,
                    "instock": true,
                    "weight": "100",
                    "dimentions": ["10", "11", "1"],
                    "material": "Metal"
          },
          {
                    "name": "Hair Pin Set of 3",
                    "id": 22,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["style"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_04.jpeg", "img/Img_04.jpeg", "img/Img_04.jpeg"],
                    "price": 100,
                    "sale": false,
                    "instock": true,
                    "weight": "120",
                    "dimentions": ["10", "11", "1"],
                    "material": "silver"
          },
          {
                    "name": "Plaine Necklace",
                    "id": 23,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["season", "style"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_05.jpeg", "img/Img_05.jpeg", "img/Img_05.jpeg"],
                    "price": 19,
                    "sale": true,
                    "instock": true,
                    "weight": "30",
                    "dimentions": ["23", "13", "2"],
                    "material": "silver"
          },
          {
                    "name": "Yuki Hair Pin Set of 3",
                    "id": 24,
                    "discription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
                    "category": ["season", "style"],
                    "main_img": "img/main_img.jpeg",
                    "img": ["img/Img_06.jpeg", "img/Img_06.jpeg", "img/Img_06.jpeg"],
                    "price": 23,
                    "sale": true,
                    "instock": false,
                    "weight": "39",
                    "dimentions": ["19", "13", "2"],
                    "material": "metal"
          },






]